//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lillian.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Lillian.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class LillianLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, TYPE=15, IDENTIFIER=16, 
		INT_LITERAL=17, STRING_LITERAL=18, COMMENT=19, ML_COMMENT=20, WS=21;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "TYPE", "IDENTIFIER", "INT_LITERAL", 
		"STRING_LITERAL", "COMMENT", "ML_COMMENT", "WS"
	};


	public LillianLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LillianLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'-'", "'*'", "'/'", "'+'", "'fun'", "'('", "')'", "':'", 
		"'{'", "'}'", "','", "'let'", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "TYPE", "IDENTIFIER", "INT_LITERAL", "STRING_LITERAL", 
		"COMMENT", "ML_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lillian.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LillianLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x17', '\x92', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', 'P', 
		'\n', '\x10', '\f', '\x10', '\xE', '\x10', 'S', '\v', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\a', '\x11', 'W', '\n', '\x11', '\f', '\x11', '\xE', '\x11', 
		'Z', '\v', '\x11', '\x3', '\x12', '\x6', '\x12', ']', '\n', '\x12', '\r', 
		'\x12', '\xE', '\x12', '^', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', 
		'\x63', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x66', '\v', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', 'k', '\n', 
		'\x13', '\f', '\x13', '\xE', '\x13', 'n', '\v', '\x13', '\x3', '\x13', 
		'\x5', '\x13', 'q', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\a', '\x14', 'w', '\n', '\x14', '\f', '\x14', 
		'\xE', '\x14', 'z', '\v', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\x82', 
		'\n', '\x15', '\f', '\x15', '\xE', '\x15', '\x85', '\v', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x6', '\x16', '\x8D', '\n', '\x16', '\r', '\x16', '\xE', '\x16', 
		'\x8E', '\x3', '\x16', '\x3', '\x16', '\x3', '\x83', '\x2', '\x17', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '\x3', '\x2', 
		'\v', '\x3', '\x2', '\x43', '\\', '\x6', '\x2', '\x32', ';', '\x43', '\\', 
		'\x61', '\x61', '\x63', '|', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\a', '\x2', '\x32', ';', '\x41', '\x41', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x3', '\x2', ')', ')', 
		'\x3', '\x2', '$', '$', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x9A', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x3', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '/', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\t', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x35', '\x3', '\x2', '\x2', '\x2', '\r', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\xF', ';', '\x3', '\x2', '\x2', '\x2', '\x11', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '?', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x17', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x45', '\x3', '\x2', '\x2', '\x2', '\x1B', 'G', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', 'K', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'M', '\x3', '\x2', '\x2', '\x2', '!', 'T', '\x3', '\x2', '\x2', '\x2', 
		'#', '\\', '\x3', '\x2', '\x2', '\x2', '%', 'p', '\x3', '\x2', '\x2', 
		'\x2', '\'', 'r', '\x3', '\x2', '\x2', '\x2', ')', '}', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x8C', '\x3', '\x2', '\x2', '\x2', '-', '.', '\a', 
		'=', '\x2', '\x2', '.', '\x4', '\x3', '\x2', '\x2', '\x2', '/', '\x30', 
		'\a', '/', '\x2', '\x2', '\x30', '\x6', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x32', '\a', ',', '\x2', '\x2', '\x32', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '\x31', '\x2', '\x2', '\x34', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\x36', '\a', '-', '\x2', '\x2', '\x36', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x38', '\a', 'h', '\x2', '\x2', '\x38', 
		'\x39', '\a', 'w', '\x2', '\x2', '\x39', ':', '\a', 'p', '\x2', '\x2', 
		':', '\xE', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '*', '\x2', '\x2', 
		'<', '\x10', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '+', '\x2', '\x2', 
		'>', '\x12', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '<', '\x2', '\x2', 
		'@', '\x14', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '}', '\x2', 
		'\x2', '\x42', '\x16', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', 
		'\x7F', '\x2', '\x2', '\x44', '\x18', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', '.', '\x2', '\x2', '\x46', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'H', '\a', 'n', '\x2', '\x2', 'H', 'I', '\a', 'g', '\x2', 
		'\x2', 'I', 'J', '\a', 'v', '\x2', '\x2', 'J', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\a', '?', '\x2', '\x2', 'L', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'Q', '\t', '\x2', '\x2', '\x2', 'N', 'P', '\t', '\x3', '\x2', 
		'\x2', 'O', 'N', '\x3', '\x2', '\x2', '\x2', 'P', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'R', ' ', '\x3', '\x2', '\x2', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'X', '\t', '\x4', '\x2', '\x2', 'U', 'W', '\t', '\x5', '\x2', 
		'\x2', 'V', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'Z', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', '\x3', '\x2', '\x2', 
		'\x2', 'Y', '\"', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', 
		'\x2', '\x2', '[', ']', '\t', '\x6', '\x2', '\x2', '\\', '[', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '\\', '\x3', 
		'\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', '_', '$', '\x3', 
		'\x2', '\x2', '\x2', '`', '\x64', '\a', ')', '\x2', '\x2', '\x61', '\x63', 
		'\n', '\a', '\x2', '\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x66', '\x3', '\x2', '\x2', '\x2', '\x64', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x65', 'g', 
		'\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'g', 'q', '\a', ')', '\x2', '\x2', 'h', 'l', '\a', '$', '\x2', '\x2', 
		'i', 'k', '\n', '\b', '\x2', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 
		'k', 'n', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', 'o', '\x3', '\x2', '\x2', '\x2', 
		'n', 'l', '\x3', '\x2', '\x2', '\x2', 'o', 'q', '\a', '$', '\x2', '\x2', 
		'p', '`', '\x3', '\x2', '\x2', '\x2', 'p', 'h', '\x3', '\x2', '\x2', '\x2', 
		'q', '&', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x31', '\x2', '\x2', 
		's', 't', '\a', '\x31', '\x2', '\x2', 't', 'x', '\x3', '\x2', '\x2', '\x2', 
		'u', 'w', '\n', '\t', '\x2', '\x2', 'v', 'u', '\x3', '\x2', '\x2', '\x2', 
		'w', 'z', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 
		'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', '{', '\x3', '\x2', '\x2', '\x2', 
		'z', 'x', '\x3', '\x2', '\x2', '\x2', '{', '|', '\b', '\x14', '\x2', '\x2', 
		'|', '(', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', '\x31', '\x2', '\x2', 
		'~', '\x7F', '\a', ',', '\x2', '\x2', '\x7F', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x82', '\v', '\x2', '\x2', '\x2', '\x81', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x85', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x83', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x86', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', ',', '\x2', '\x2', '\x87', 
		'\x88', '\a', '\x31', '\x2', '\x2', '\x88', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x89', '\x8A', '\b', '\x15', '\x2', '\x2', '\x8A', '*', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8D', '\t', '\n', '\x2', '\x2', '\x8C', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x90', 
		'\x91', '\b', '\x16', '\x2', '\x2', '\x91', ',', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x2', 'Q', 'X', '^', '\x64', 'l', 'p', 'x', '\x83', '\x8E', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Lillian.Parser
